### ISSUE TITLE
Google Drive fails on Google Docs files

### ISSUE THREAD

**Issue by shinji257** [AlexCSDev/UniversalDownloaderPlatform#11]
It doesn't just fail.  It stops downloading from the URL entirely if it hits an error with any files.  In this example it happens to be the first file and it doesn't bother to retrieve any of the other files or folders at the link.

```
2022-01-31 16:59:42.9332 ERROR Failed to download https://drive.google.com/drive/folders/1BlIN7f7OyQjTa55DgMeshd3clCJNszI8?usp=sharing: Error while downloading https://drive.google.com/drive/folders/1BlIN7f7OyQjTa55DgMeshd3clCJNszI8?usp=sharing: Unable to download https://drive.google.com/drive/folders/1BlIN7f7OyQjTa55DgMeshd3clCJNszI8?usp=sharing. Inner Exception: System.Exception: Unable to download PLEASE, ANSWER THIS SURVEY AFTER READING :): The service drive has thrown an exception: Google.GoogleApiException: Google.Apis.Requests.RequestError
Only files with binary content can be downloaded. Use Export with Docs Editors files. [403]
Errors [
        Message[Only files with binary content can be downloaded. Use Export with Docs Editors files.] Location[alt - parameter] Reason[fileNotDownloadable] Domain[global]
]

   at Google.Apis.Download.MediaDownloader.DownloadCoreAsync(String url, Stream stream, CancellationToken cancellationToken)
   at UniversalDownloaderPlatform.GoogleDriveDownloader.GoogleDriveEngine.DownloadFileResource(File fileResource, String path, Boolean rootPath, Boolean overwrite)
   at UniversalDownloaderPlatform.GoogleDriveDownloader.GoogleDriveEngine.DownloadFileResource(File fileResource, String path, Boolean rootPath, Boolean overwrite)
   at UniversalDownloaderPlatform.GoogleDriveDownloader.GoogleDriveEngine.Download(String id, String path, Boolean overwrite)
   at UniversalDownloaderPlatform.GoogleDriveDownloader.Plugin.Download(ICrawledUrl crawledUrl, String downloadDirectory)
   ```
   
   EDIT: Warning -- The content at the url reference in the error is NSFW.  Just a heads up on that.

**Comment by AlexCSDev** [comment]
Google Docs should work fine now. The changes will propagate to PatreonDownloader in the next release.
